import urllib.request
import ssl
import certifi
import os

# Players to search
player_codes = [
    "youngtr01",  # Trae Young (Atlanta Hawks)
    "murrade01",  # Dejounte Murray (Atlanta Hawks)
    "capelca01",  # Clint Capela (Atlanta Hawks)
    "tatumja01",  # Jayson Tatum (Boston Celtics)
    "brownja02",  # Jaylen Brown (Boston Celtics)
    "porzikr01",  # Kristaps Porziņģis (Boston Celtics)
    "bridgmi01",  # Mikal Bridges (Brooklyn Nets)
    "johnsca02",  # Cam Johnson (Brooklyn Nets)
    "claxtni01",  # Nic Claxton (Brooklyn Nets)
    "ballla01",  # LaMelo Ball (Charlotte Hornets)
    "millebr02",  # Brandon Miller (Charlotte Hornets)
    "curryse01",  # Seth Curry (Charlotte Hornets)
    "lavinza01",  # Zach LaVine (Chicago Bulls)
    "derozde01",  # DeMar DeRozan (Chicago Bulls)
    "vucevni01",  # Nikola Vučević (Chicago Bulls)
    "mitchdo01",  # Donovan Mitchell (Cleveland Cavaliers)
    "garland01",  # Darius Garland (Cleveland Cavaliers)
    "moblee01",  # Evan Mobley (Cleveland Cavaliers)
    "cunnica01",  # Cade Cunningham (Detroit Pistons)
    "iveyja01",  # Jaden Ivey (Detroit Pistons)
    "thompau01",  # Ausar Thompson (Detroit Pistons)
    "halibty01",  # Tyrese Haliburton (Indiana Pacers)
    "turnemy01",  # Myles Turner (Indiana Pacers)
    "mathube01",  # Bennedict Mathurin (Indiana Pacers)
    "butleji01",  # Jimmy Butler (Miami Heat)
    "adebaba01",  # Bam Adebayo (Miami Heat)
    "herroty01",  # Tyler Herro (Miami Heat)
    "antetgi01",  # Giannis Antetokounmpo (Milwaukee Bucks)
    "lillada01",  # Damian Lillard (Milwaukee Bucks)
    "portibo01",  # Bobby Portis (Milwaukee Bucks)
    "brunsonj01",  # Jalen Brunson (New York Knicks)
    "randlju01",  # Julius Randle (New York Knicks)
    "barretj01",  # RJ Barrett (New York Knicks)
    "banchpa01",  # Paolo Banchero (Orlando Magic)
    "wagnefr01",  # Franz Wagner (Orlando Magic)
    "cartewe01",  # Wendell Carter Jr. (Orlando Magic)
    "embiidj01",  # Joel Embiid (Philadelphia 76ers)
    "maxety01",  # Tyrese Maxey (Philadelphia 76ers)
    "harrito02",  # Tobias Harris (Philadelphia 76ers)
    "siakapa01",  # Pascal Siakam (Toronto Raptors)
    "barnesc01",  # Scottie Barnes (Toronto Raptors)
    "anunoog01",  # OG Anunoby (Toronto Raptors)
    "poolejo01",  # Jordan Poole (Washington Wizards)
    "kuzmaky01",  # Kyle Kuzma (Washington Wizards)
    "jonesty01",  # Tyus Jones (Washington Wizards)
    "doncilu01",  # Luka Dončić (Dallas Mavericks)
    "irvinky01",  # Kyrie Irving (Dallas Mavericks)
    "willigr01",  # Grant Williams (Dallas Mavericks)
    "jokicni01",  # Nikola Jokić (Denver Nuggets)
    "murrayja01",  # Jamal Murray (Denver Nuggets)
    "portemi01",  # Michael Porter Jr. (Denver Nuggets)
    "curryst01",  # Stephen Curry (Golden State Warriors)
    "thompsk01",  # Klay Thompson (Golden State Warriors)
    "greendr01",  # Draymond Green (Golden State Warriors)
    "vanvlf01",  # Fred VanVleet (Houston Rockets)
    "greenja05",  # Jalen Green (Houston Rockets)
    "sengual01",  # Alperen Şengün (Houston Rockets)
    "leonaka01",  # Kawhi Leonard (Los Angeles Clippers)
    "georpau01",  # Paul George (Los Angeles Clippers)
    "westbru01",  # Russell Westbrook (Los Angeles Clippers)
    "jamesle01",  # LeBron James (Los Angeles Lakers)
    "davisan02",  # Anthony Davis (Los Angeles Lakers)
    "reaveau01",  # Austin Reaves (Los Angeles Lakers)
    "moranja01",  # Ja Morant (Memphis Grizzlies)
    "jackja02",  # Jaren Jackson Jr. (Memphis Grizzlies)
    "banede01",  # Desmond Bane (Memphis Grizzlies)
    "edwaran01",  # Anthony Edwards (Minnesota Timberwolves)
    "townska01",  # Karl-Anthony Towns (Minnesota Timberwolves)
    "goberru01",  # Rudy Gobert (Minnesota Timberwolves)
    "willizi01",  # Zion Williamson (New Orleans Pelicans)
    "ingrabr01",  # Brandon Ingram (New Orleans Pelicans)
    "mccolcj01",  # CJ McCollum (New Orleans Pelicans)
    "gilgesh01",  # Shai Gilgeous-Alexander (Oklahoma City Thunder)
    "giddejo01",  # Josh Giddey (Oklahoma City Thunder)
    "holmgch01",  # Chet Holmgren (Oklahoma City Thunder)
    "duranke01",  # Kevin Durant (Phoenix Suns)
    "bookede01",  # Devin Booker (Phoenix Suns)
    "bealbr01",  # Bradley Beal (Phoenix Suns)
    "hendesc01",  # Scoot Henderson (Portland Trail Blazers)
    "simonan01",  # Anfernee Simons (Portland Trail Blazers)
    "aytonde01",  # Deandre Ayton (Portland Trail Blazers)
    "foxde01",  # De'Aaron Fox (Sacramento Kings)
    "sabondo01",  # Domantas Sabonis (Sacramento Kings)
    "murrake02",  # Keegan Murray (Sacramento Kings)
    "wembavi01",  # Victor Wembanyama (San Antonio Spurs)
    "johnske04",  # Keldon Johnson (San Antonio Spurs)
    "vassede01",  # Devin Vassell (San Antonio Spurs)
    "markkla01",  # Lauri Markkanen (Utah Jazz)
    "kesslwa01",  # Walker Kessler (Utah Jazz)
    "clarkjo01",  # Jordan Clarkson (Utah Jazz)
]



ssl_context = ssl.create_default_context(cafile=certifi.where())
os.makedirs('raw_player_images', exist_ok=True)


url_template = "https://www.basketball-reference.com/req/202106291/images/headshots/{0}.jpg"

for player_code in player_codes:
    url = url_template.format(player_code, player_code)
    with urllib.request.urlopen(url, context=ssl_context) as response:
        with open(f"{player_code}.jpg", 'wb') as out_file:
            out_file.write(response.read())